# Generated by Django 3.2 on 2021-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_auto_20210623_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturetool',
            name='personalimage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
