# Generated by Django 3.2 on 2021-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_alter_signaturetool_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturetool',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signaturetool',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
